### ISSUE TITLE
Source of the Map files.

### ISSUE THREAD

**Issue by ndo360** [ptown2/Garrychet#3]
Is it possible to get the vmf files to the test maps? I'm got a mapper who needs the source to the test maps to know what to add into the map that the gamemode calls.

**Comment by ptown2** [comment]
I don't really have em, neither the original maker does. Honestly, you probably won't need them since you have the FGD file in GitHub, which is useful for source mapping since its pre-defined entity properties you have to slap on by defining them.

**Comment by ndo360** [comment]
Yea I decompiled it and got what I needed in order to apply it to other maps. 
(Hence the new Beta Map! ^-^)
